### ISSUE TITLE
Error about regex

### ISSUE THREAD

**Issue by vleedev** [step-/JSON.awk#14] opened 2019-04-24 12:56 UTC
I got this problem.
`awk: ./JSON.awk:258: warning: regexp escape sequence `\"' is not a known regexp operator`

it's just a warning. But the result is ok.

**Comment by step-** [comment] 2019-04-25 08:28
Thank you for your report.  That line was added in commit 19ee376 to address issue #1. I hasn't changed since then.
* Which awk (gawk, mawk, busybox awk, ...) are you running and which version?
* Which OS?
* Does this [JSON text](https://github.com/step-/JSON.awk/blob/master/test-cases/20130418-issue-001-test.json) trigger the same warning message?
  * If not, can you please attach the JSON input text that triggers the warning message?

**Comment by leetuanit** [comment] 2019-04-26 03:58
I was running it on my macbook. And I got this warning. But with ubuntu and centos are ok. I installed gawk and mawk with the newest version. I used to try this in my friend's mac, and it's still the same.

**Comment by step-** [comment] 2019-04-27 09:08
According to [wikipedia](https://en.wikipedia.org/wiki/AWK#Versions_and_implementations) mac OS uses nawk, which I've never come across. If you can attach the JSON text that triggers the warning message I  will test it on a friend's macbook and try to clear the message.
I understand that despite the message JSON.awk worked for you so I'm marking this issue as an enhancement request.
Thank you

**Comment by mohd-akram** [comment] 2020-08-15 13:16
I encountered this too - the issue is that quotes shouldn't be escaped inside a regex. See the fix [here](https://github.com/mohd-akram/jawk/commit/de1b611401d8b1a9dfd316dfc8772bc278499ff1).

**Comment by step-** [comment] 2020-08-15 14:34
Thank you.  According to the table []()
> Using a `<slash>` character within an ERE requires the escaping shown in the following table.

| Escape Sequence | Description | Meaning |
|-|-|-|
\\" | `<backslash>` `<quotation-mark>` | `<quotation-mark>` character |
...

It seems to me the rule says that `"` within an ERE should be escaped, and your fix shouldn't be needed as going against the rule.

However, splitting hairs, whether the "within" means that the opening and closing slash characters that delimit the ERE shouldn't be considered to apply the rule I'm left to wonder.  How do you interpret that phrase?  I'm asking because none of the EREs we use include a slash inside the delimiters therefore one could argue that the rule doesn't apply, that `"` may not be escaped, and your fix is legitimate.

**Comment by mohd-akram** [comment] 2020-08-15 14:52
They've fixed this in the current POSIX draft (see [here](https://austingroupbugs.net/view.php?id=1105), download from [here](https://www.opengroup.org/austin/restricted/)). `\"` and `\/` are only specified in a string and ERE respectively. The new wording:


Escape Sequence  | Description  |  Meaning
-- | -- | --
\\" | \<backslash\> \<quotation-mark\> | In the lexical token **STRING**, \<quotation-mark\> character. Otherwise undefined.
\\/ | \<backslash\> \<slash\> | In the lexical token **ERE**, \<slash\> character. Otherwise undefined.

**Comment by step-** [comment] 2020-08-15 15:03
OK, thank you.  It's still a draft but I will take it as authoritative. However, before committing a fix I need to test it with mawk and busybox awk because I've been bitten in the past.  The title of your commit says "Fix gawk warning".  I've never seen that warning on Linux.  Which version of gawk did you use?  Mine is 4.2.0  (I was using 4.1.0 and 4.1.1 before but still I can't remember having seen that warning).

**Comment by mohd-akram** [comment] 2020-08-15 15:42
I used gawk 5.1.0.

**Comment by step-** [comment] 2020-08-15 16:07
Thank you.  I built gawk 5.1.0 in my Linux box and can see the warning too.

**Comment by step-** [comment] 2020-08-18 15:30
Closed b7b7826da88dd9d7ba946310cce9adf93178567d

**Closed by step-** 2020-08-18 15:30 UTC
Labels: enhancement
